/**
 * generated by Xtext 2.12.0
 */
package iDM_Test.generator;

import fr.inria.diverse.k3.al.annotationprocessor.Aspect;
import fr.inria.diverse.k3.al.annotationprocessor.Step;
import iDM_Test.Transition;
import iDM_Test.generator.TransitionAspectTransitionAspectProperties;

@Aspect(className = Transition.class)
@SuppressWarnings("all")
public class TransitionAspect {
  @Step
  public static void fire(final Transition _self) {
    final iDM_Test.generator.TransitionAspectTransitionAspectProperties _self_ = iDM_Test.generator.TransitionAspectTransitionAspectContext.getSelf(_self);
    fr.inria.diverse.k3.al.annotationprocessor.stepmanager.StepCommand command = new fr.inria.diverse.k3.al.annotationprocessor.stepmanager.StepCommand() {
    	@Override
    	public void execute() {
    		_privk3_fire(_self_, _self);
    	}
    };
    fr.inria.diverse.k3.al.annotationprocessor.stepmanager.IStepManager stepManager = fr.inria.diverse.k3.al.annotationprocessor.stepmanager.StepManagerRegistry.getInstance().findStepManager(_self);
    if (stepManager != null) {
    	stepManager.executeStep(_self,command,"Transition","fire");
    } else {
    	command.execute();
    }
    ;;
  }
  
  protected static void _privk3_fire(final TransitionAspectTransitionAspectProperties _self_, final Transition _self) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field fsm is undefined for the type State"
      + "\nThe method or field action is undefined for the type Transition"
      + "\ncurrentState cannot be resolved"
      + "\noutputBuffer cannot be resolved"
      + "\nenqueue cannot be resolved"
      + "\nconsummedString cannot be resolved"
      + "\nconsummedString cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nunderProcessTrigger cannot be resolved");
  }
}
