/*
 * generated by Xtext 2.12.0
 */
package iDM_Test


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class StateMachineRuntimeModule extends AbstractStateMachineRuntimeModule {
}
