/**
 * generated by Xtext 2.12.0
 */
package iDM_Test.ide;

import iDM_Test.ide.AbstractStateMachineIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class StateMachineIdeModule extends AbstractStateMachineIdeModule {
}
