/**
 * generated by Xtext 2.12.0
 */
package iDM_Test.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import iDM_Test.StateMachineRuntimeModule;
import iDM_Test.StateMachineStandaloneSetup;
import iDM_Test.ide.StateMachineIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class StateMachineIdeSetup extends StateMachineStandaloneSetup {
  @Override
  public Injector createInjector() {
    StateMachineRuntimeModule _stateMachineRuntimeModule = new StateMachineRuntimeModule();
    StateMachineIdeModule _stateMachineIdeModule = new StateMachineIdeModule();
    return Guice.createInjector(Modules2.mixin(_stateMachineRuntimeModule, _stateMachineIdeModule));
  }
}
