/*
 * generated by Xtext 2.12.0
 */
package iDM_Test.ui;

import com.google.inject.Injector;
import iDM_Test.StateMachine.ui.internal.StateMachineActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StateMachineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StateMachineActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StateMachineActivator.getInstance().getInjector(StateMachineActivator.IDM_TEST_STATEMACHINE);
	}
	
}
