/**
 * generated by Xtext 2.12.0
 */
package iDM_Test;

import iDM_Test.AbstractStateMachineRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StateMachineRuntimeModule extends AbstractStateMachineRuntimeModule {
}
