/**
 * generated by Xtext 2.12.0
 */
package iDM_Test;

import iDM_Test.StateMachineStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class StateMachineStandaloneSetup extends StateMachineStandaloneSetupGenerated {
  public static void doSetup() {
    new StateMachineStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
