/*
 * generated by Xtext 2.12.0
 */
package iDM_Test.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StateMachineAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("iDM_Test/parser/antlr/internal/InternalStateMachine.tokens");
	}
}
