/**
 * generated by Xtext 2.12.0
 */
package iDM_Test.ui.contentassist;

import iDM_Test.ui.contentassist.AbstractStateMachineProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class StateMachineProposalProvider extends AbstractStateMachineProposalProvider {
}
