/*
 * generated by Xtext 2.12.0
 */
package iDM_Test.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class StateMachineGrammarAccess extends AbstractGrammarElementFinder {
	
	public class StateMachineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "iDM_Test.StateMachine.StateMachine");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cStateMachineAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cStateMachineKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_0_2_0 = (RuleCall)cNameAssignment_0_2.eContents().get(0);
		private final Group cGroup_0_3 = (Group)cGroup_0.eContents().get(3);
		private final Keyword cStateKeyword_0_3_0 = (Keyword)cGroup_0_3.eContents().get(0);
		private final Assignment cStatesAssignment_0_3_1 = (Assignment)cGroup_0_3.eContents().get(1);
		private final RuleCall cStatesStateParserRuleCall_0_3_1_0 = (RuleCall)cStatesAssignment_0_3_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cGroup_1.eContents().get(0);
		private final Keyword cTransitionKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cTransitionAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cTransitionTransitionParserRuleCall_1_0_1_0 = (RuleCall)cTransitionAssignment_1_0_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cInitKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cInitAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cInitStateParserRuleCall_1_1_1_0 = (RuleCall)cInitAssignment_1_1_1.eContents().get(0);
		
		//StateMachine:
		//	{StateMachine}
		//	'StateMachine'
		//	name=EString ('state' states+=State) | ('transition' transition+=Transition) ('init' init=State);
		@Override public ParserRule getRule() { return rule; }
		
		//{StateMachine} 'StateMachine' name=EString ('state' states+=State) | ('transition' transition+=Transition) ('init'
		//init=State)
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{StateMachine} 'StateMachine' name=EString ('state' states+=State)
		public Group getGroup_0() { return cGroup_0; }
		
		//{StateMachine}
		public Action getStateMachineAction_0_0() { return cStateMachineAction_0_0; }
		
		//'StateMachine'
		public Keyword getStateMachineKeyword_0_1() { return cStateMachineKeyword_0_1; }
		
		//name=EString
		public Assignment getNameAssignment_0_2() { return cNameAssignment_0_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_2_0() { return cNameEStringParserRuleCall_0_2_0; }
		
		//'state' states+=State
		public Group getGroup_0_3() { return cGroup_0_3; }
		
		//'state'
		public Keyword getStateKeyword_0_3_0() { return cStateKeyword_0_3_0; }
		
		//states+=State
		public Assignment getStatesAssignment_0_3_1() { return cStatesAssignment_0_3_1; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_0_3_1_0() { return cStatesStateParserRuleCall_0_3_1_0; }
		
		//('transition' transition+=Transition) ('init' init=State)
		public Group getGroup_1() { return cGroup_1; }
		
		//'transition' transition+=Transition
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'transition'
		public Keyword getTransitionKeyword_1_0_0() { return cTransitionKeyword_1_0_0; }
		
		//transition+=Transition
		public Assignment getTransitionAssignment_1_0_1() { return cTransitionAssignment_1_0_1; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_1_0_1_0() { return cTransitionTransitionParserRuleCall_1_0_1_0; }
		
		//'init' init=State
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'init'
		public Keyword getInitKeyword_1_1_0() { return cInitKeyword_1_1_0; }
		
		//init=State
		public Assignment getInitAssignment_1_1_1() { return cInitAssignment_1_1_1; }
		
		//State
		public RuleCall getInitStateParserRuleCall_1_1_1_0() { return cInitStateParserRuleCall_1_1_1_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "iDM_Test.StateMachine.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "iDM_Test.StateMachine.State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStateAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//State:
		//	{State} name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{State} name=EString
		public Group getGroup() { return cGroup; }
		
		//{State}
		public Action getStateAction_0() { return cStateAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "iDM_Test.StateMachine.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cOpenKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cCloseKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cFromAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cFromStateCrossReference_1_0 = (CrossReference)cFromAssignment_1.eContents().get(0);
		private final RuleCall cFromStateEStringParserRuleCall_1_0_1 = (RuleCall)cFromStateCrossReference_1_0.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cToAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cToStateCrossReference_3_0 = (CrossReference)cToAssignment_3.eContents().get(0);
		private final RuleCall cToStateEStringParserRuleCall_3_0_1 = (RuleCall)cToStateCrossReference_3_0.eContents().get(1);
		
		//Transition:
		//	('open' | 'close') from=[State|EString] '->' to=[State|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//('open' | 'close') from=[State|EString] '->' to=[State|EString]
		public Group getGroup() { return cGroup; }
		
		//'open' | 'close'
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'open'
		public Keyword getOpenKeyword_0_0() { return cOpenKeyword_0_0; }
		
		//'close'
		public Keyword getCloseKeyword_0_1() { return cCloseKeyword_0_1; }
		
		//from=[State|EString]
		public Assignment getFromAssignment_1() { return cFromAssignment_1; }
		
		//[State|EString]
		public CrossReference getFromStateCrossReference_1_0() { return cFromStateCrossReference_1_0; }
		
		//EString
		public RuleCall getFromStateEStringParserRuleCall_1_0_1() { return cFromStateEStringParserRuleCall_1_0_1; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//to=[State|EString]
		public Assignment getToAssignment_3() { return cToAssignment_3; }
		
		//[State|EString]
		public CrossReference getToStateCrossReference_3_0() { return cToStateCrossReference_3_0; }
		
		//EString
		public RuleCall getToStateEStringParserRuleCall_3_0_1() { return cToStateEStringParserRuleCall_3_0_1; }
	}
	
	
	private final StateMachineElements pStateMachine;
	private final EStringElements pEString;
	private final StateElements pState;
	private final TransitionElements pTransition;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public StateMachineGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pStateMachine = new StateMachineElements();
		this.pEString = new EStringElements();
		this.pState = new StateElements();
		this.pTransition = new TransitionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("iDM_Test.StateMachine".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//StateMachine:
	//	{StateMachine}
	//	'StateMachine'
	//	name=EString ('state' states+=State) | ('transition' transition+=Transition) ('init' init=State);
	public StateMachineElements getStateMachineAccess() {
		return pStateMachine;
	}
	
	public ParserRule getStateMachineRule() {
		return getStateMachineAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//State:
	//	{State} name=EString;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//Transition:
	//	('open' | 'close') from=[State|EString] '->' to=[State|EString];
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
