/**
 * generated by Xtext 2.12.0
 */
package iDM_Test.validation;

import iDM_Test.validation.AbstractStateMachineValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StateMachineValidator extends AbstractStateMachineValidator {
}
