/**
 * generated by Xtext 2.12.0
 */
package iDM_Test.formatting2;

import com.google.inject.Inject;
import iDM_Test.StateMachine;
import iDM_Test.services.StateMachineGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class StateMachineFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private StateMachineGrammarAccess _stateMachineGrammarAccess;
  
  protected void _format(final StateMachine stateMachine, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field getInit is undefined for the type StateMachine"
      + "\nformat cannot be resolved");
  }
  
  public void format(final Object stateMachine, final IFormattableDocument document) {
    if (stateMachine instanceof XtextResource) {
      _format((XtextResource)stateMachine, document);
      return;
    } else if (stateMachine instanceof StateMachine) {
      _format((StateMachine)stateMachine, document);
      return;
    } else if (stateMachine instanceof EObject) {
      _format((EObject)stateMachine, document);
      return;
    } else if (stateMachine == null) {
      _format((Void)null, document);
      return;
    } else if (stateMachine != null) {
      _format(stateMachine, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(stateMachine, document).toString());
    }
  }
}
