/*
 * generated by Xtext 2.12.0
 */
package iDM_Test.formatting2

import com.google.inject.Inject
import iDM_Test.State
import iDM_Test.StateMachine
import iDM_Test.Transition
import iDM_Test.services.StateMachineGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class StateMachineFormatter extends AbstractFormatter2 {
	
	@Inject extension StateMachineGrammarAccess

	def dispatch void format(StateMachine stateMachine, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (State state : stateMachine.getStates()) {
			state.format;
		}
		for (Transition transition : stateMachine.getTransition()) {
			transition.format;
		}
		stateMachine.getInit.format;
	}
	
	// TODO: implement for 
}
