/*
 * generated by Xtext 2.12.0
 */
package iDM_Test.ui.tests;

import com.google.inject.Injector;
import iDM_Test.StateMachine.ui.internal.StateMachineActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class StateMachineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StateMachineActivator.getInstance().getInjector("iDM_Test.StateMachine");
	}

}
