/**
 * generated by Xtext 2.12.0
 */
package iDM_Test.ui;

import iDM_Test.ui.AbstractStateMachineUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StateMachineUiModule extends AbstractStateMachineUiModule {
  public StateMachineUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
